---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dso-demo-java
  namespace: dso-demo-java
  labels:
    app: dso-demo-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo-java
  template:
    metadata:
      labels:
        app: dso-demo-java
    spec:
      imagePullSecrets:
        - name: quay-image-pull-secret
      containers:
        - name: dso-demo-java
          image: quay.apps.ocp4-8.infocepo.com/ministere-interieur-candilib-forge-dso/app-java-forge-dso-demo:912efb0
          imagePullPolicy: Always
          env:
            - name: PG_USER
              value: "pg_user"
            - name: PG_PASSWORD
              value: "My$ecrETPAss0rd*"
            - name: MONGO_URL
              value: mongodb://$(PG_USER):$(PG_PASSWORD)@postgres/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: $(PG_USER)
            - name: SPRING_DATASOURCE_PASSWORD
              value: $(PG_PASSWORD)
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080  # Exposes container port