apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: ministere-interieur-demo-projets-dso-clients-dev